//bpa pour bodypart antérieure
export const bpa = { 
    tete: "Tête (ant.)",
    couG: "Cou (G)",
    couD: "Cou (D)",
    trapG: "Trapèze gauche",
    trapD: "Trapèze droit",

    epG: "Épaule gauche (ant.)",
    epD: "Épaule droite (ant.)",
    biG: "Biceps gauche",
    biD: "Biceps droit",
    coudG: "Coude gauche (ant.)",
    coudD: "Coude droit (ant.)",
    avbG: "Avant-bras gauche (ant.) (fléchisseurs)",
    avbD: "Avant-bras droit (ant.) (fléchisseurs)",
    poiG: "Poignet gauche (ant.)",
    poiD: "Poignet droit (ant.)",
    mainG: "Main gauche (ant.) (face palmaire)",
    mainD: "Main droite (ant.) (face palmaire)",

    pecG: "Pectoral gauche",
    pecD: "Pectoral droit",
    cotG: "Côtes gauches",
    cotD: "Côtes droites",
    abdG: "Adbominaux gauches",
    abdD: "Abdominaux droits",
    oblG: "Obliques gauches",
    oblD: "Obliques droits",

    hanG: "Hanche gauche",
    hanD: "Hanche droite",
    quadG: "Quadriceps gauche",
    quadD: "Quadriceps droit",
    addG: "Adducteur gauche",
    addD: "Adducteur droit",
    genG: "Genou gauche (ant.)",
    genD: "Genou droit (ant.)",
    tibG: "Tibia gauche",
    tibD: "Tibia droit",
    cheG: "Cheville gauche (ant.)",
    cheD: "Cheville droite (ant.)",
    pieG: "Pied gauche",
    pieD: "Pied droit"    
}

export const bpp = {
    tete: "Tête (post.)",
    trapG: "Trapèze gauche",
    trapD: "Trapèze droit",

    epG: "Epaule gauche (post.)",
    epD: "Epaule droite (post.)",
    triG: "Triceps gauche",
    triD: "Triceps droit",
    couG: "Coude gauche (post.)",
    couD: "Coude droit (post.)",
    avbG: "Avant-bras gauche (post.) (extenseurs)",
    avbD: "Avant-bras droit (post.) (extenseurs)",
    poiG: "Poignet gauche (post.)",
    poiD: "Poignet droit (post.)",
    mainG: "Main gauche (post.) (face dorsale)",
    mainD: "Main droit (post.) (face dorsale)",

    col: "Colonne vertébrale",
    scaG: "Région scapulaire gauche",
    scaD: "Région scapulaire droite",
    dosG: "Dos (flanc gauche)",
    dosD: "Dos (flanc droit)",
    lombG: "Lombaire gauche",
    lombD: "Lombaire droit",

    fesG: "Fesse gauche",
    fesD: "Fesse droite",
    iscG: "Ischios gauches",
    iscD: "Ischios droits",
    genG: "Genou gauche (post.)",
    genD: "Genou droit (post.)",
    molG: "Mollet gauche",
    molD: "Mollet droit",
    cheG: "Cheville gauche (post.)",
    cheD: "Chevile droite (post.)",
    pieG: "Pied gauche (post.)",
    pieD: "Pied droit (post.)"
}